### ISSUE TITLE
Support WebGL？

### ISSUE THREAD

**Issue by lemon-li** [robertohuertasm/SQLite4Unity3d#80]
I want to convert my project to WebGL , but the sqlite3 may not support 。

**Comment by yggoon** [comment]
form me is not working on WebGL could any one tell me that is normal that WebGL is not supported in this project?

**Comment by lemon-li** [comment]
@yggoon 
I use a new solution.
it supports webgl platform.
[IboxDB](http://www.iboxdb.com/)
