### ISSUE TITLE
Is there any guide to compile the Android ARM64 version of .so file?

### ISSUE THREAD

**Issue by JustinFincher** [robertohuertasm/SQLite4Unity3d#92]
Hi, Thanks for the solution, it's embedded in the Mapbox Unity SDK and used in my project, which was doing well until when I tried to build the Unity project with il2pp and arm64 support, and I found there wasn't an arm64 version .so file.
It seems this repo has not been updated in a while, and I am thinking if I can find the android source and compile it myself, is there any guide on the android plugin?

Related issue: https://github.com/mapbox/mapbox-unity-sdk/issues/976

**Comment by Vangaorth** [comment]
You can just compile the SQLite source code using the Android-NDK. Just follow [this guide](https://ornithoptergames.com/how-to-set-up-sqlite-for-unity/) under the "3. Android support" section.

**Comment by dorukeker** [comment]
https://github.com/mapbox/mapbox-unity-sdk/issues/1331
