### ISSUE TITLE
Android Arm64 support

### ISSUE THREAD

**Issue by BigGiantHead** [robertohuertasm/SQLite4Unity3d#98]
Hi,

I'm trying to make my Unity3D app work IL2CPP and Arm64. As much as I can see there is no .so file for this platform. I will really appreciate if you can let me know how to do this.

Thanks.

**Comment by ourgames** [comment]
> Hi,
> 
> I'm trying to make my Unity3D app work IL2CPP and Arm64. As much as I can see there is no .so file for this platform. I will really appreciate if you can let me know how to do this.
> 
> Thanks.

Did you get it done? I meet the same problem!

**Comment by BigGiantHead** [comment]
@ourgames unfortunately I haven't, and I haven't had the time to put into finding a solution. I think I'm gonna have to switch to a .Net/Mono implementation, I used a while ago, but will also take time. :(

**Comment by mikavaliviita** [comment]
Hi,

@robertohuertasm , what is your opinion about Android ARM64 version?

Thanks,

**Comment by robertohuertasm** [comment]
Hi @mikavaliviita, I don't have any opinion on this matter. I'm not really dedicated to this plugin anymore as I'm not working with Unity3D at the moment so hopefully some member from the community should be able to send a PR with the proper .so.

**Comment by mikavaliviita** [comment]
Thank you @robertohuertasm for answering and for the info! It is valuable to know the current state of the project.

Are there sources available to these library files?

Thanks,

**Comment by cabanel** [comment]
Hi,

I made at least 6 projects with this beautiful library. Today
I received a message from google:

By August 1, 2019, all apps that use native code must provide a 64-bit version in addition to the 32-bit version in order to publish an update. This past January, we reiterated that this is required in order to make way for innovation and in anticipation of future Android devices that only support 64-bit code.
As the deadline approaches, we wanted to remind you that at least one of your apps* uses native code but does not currently offer a 64-bit variant:

how can we solve?

thanks

**Comment by mikavaliviita** [comment]
Hi @robertohuertasm ,

I'm willing to compile and send a PR for the 64bit version, just give me a pointer for the sources of where the 32bit version was compiled from.

Thanks,

**Comment by BigGiantHead** [comment]
Hey guys,

Just built the Arm 64 .so. Works for me in Unity. 
You can download it from the link: https://www.dropbox.com/s/907rlmf0kjr7akq/arm64-v8a.zip?dl=0

By the way how can I become a contributor to this repository, so I can add the .so file. Should I just PR it?

**Comment by BigGiantHead** [comment]
Hi @robertohuertasm,

Pull requested the libsqlite3.so file to your fork.

**Comment by cabanel** [comment]
Thanks for the file!!!
How can I force the 64-bit test on my device? can i remove the 32bit and try it if it works?

**Comment by BigGiantHead** [comment]
Well, if you enable IL2CPP and enable Arm64 and your device supports 64 bit
it will use it.
If you want to, you can just leave Arm64 enabled and disable the rest. I
tried it both ways.

**Comment by cabanel** [comment]
Thanks!!!

**Comment by mikavaliviita** [comment]
Hi @BigGiantHead and @robertohuertasm ,

I can confirm this to be working.

Thank you @BigGiantHead
